Repository elementary/tasks, pull requests merged in 2021-09, with the labels that each got.

#300 MainWindow: copy and icon for delete confirmation dialog
  src/MainWindow.vala
Labels: Bitesize

#286 Fixes an Issue when removing task description
  data/tasks.appdata.xml.in
  src/Widgets/TaskRow.vala
Labels: Bitesize, Bug

#295 Load only non-completed tasks by default
  data/tasks.appdata.xml.in
  src/Widgets/TaskListGrid.vala
Labels: Bug

#293 Fix cursor placing on focus
  data/tasks.appdata.xml.in
  src/Widgets/TaskRow.vala
Labels: Bitesize, UX
