Repository elementary/tasks, pull requests merged in 2021-12, with the labels that each got.

#314 Granite.HyperTextView: Support for clickable hyperlinks in task description
  README.md
  data/tasks.appdata.xml.in
  meson.build
  src/Widgets/TaskRow.vala
Labels: Bitesize

#296 Drag Task to another List
  data/SourceRow.css
  data/TaskRow.css
  data/tasks.appdata.xml.in
  src/Application.vala
  src/TaskModel.vala
  src/Widgets/SourceRow.vala
  src/Widgets/TaskRow.vala
Labels: Enhancement

#313 Use floating timezones when saving timed tasks
  src/Util.vala
  src/Widgets/ScheduledTaskListGrid.vala
  src/Widgets/TaskRow.vala
Labels: Needs Design

#316 Release 6.1.0
  data/tasks.appdata.xml.in
  meson.build
Labels: Release

#298 Notifications
  data/daemon.desktop
  data/meson.build
  data/tasks.desktop.in
  meson.build
  src/Application.vala
  src/TaskModel.vala
  src/TodayTaskMonitor.vala
  src/Util.vala
  src/Widgets/TaskRow.vala
Labels: Enhancement
